site_name: side-projects/data-mesh
docs_dir: docs
nav:
  - index.md
  - products-s3-biglake-table.md
  - images-gcs-object-table.md
  - combined.md
  - rag.md

theme:
  name: material
  features:
    - content.tabs.link
    - content.code.copy
    - content.code.annotate 

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - footnotes
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets:
      url_download: true
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.details
  - pymdownx.blocks.caption
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - glightbox
  - search
  - mkdocs-jupyter # mkdocs-jupyter==0.25.1
  - enumerate-headings:
      toc_depth: 0
      increment_across_pages: false